[package]
name        = "cmp-basic"
version     = "0.1.0"
standard    = "c++23"
description = "Basic consumer for the mcpplibs.cmp module"
license     = "Apache-2.0"

[dependencies.mcpplibs]
cmp = { path = "../.." }
